In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0'

In [3]:
x = tf.constant('hola mundo')
x

<tf.Tensor: shape=(), dtype=string, numpy=b'hola mundo'>

In [4]:
a = tf.constant(2)
b = tf.constant(4)
c = a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [5]:
a1 = tf.constant([10, 20])
b1 = tf.constant([1, 2])
c1 = a1 + b1
c1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([11, 22], dtype=int32)>